### ISSUE TITLE
Stuck at "Starting anisette_server" on Fedora 36

### ISSUE THREAD

**Issue by 2vergent** [altlinux-team/AltLinux#2]
While doing the **python3 main.py** command, Altlinux opens and is stuck at "**Starting anisette_server**".  The terminal shows the error **curl: (7) Failed to connect to 127.0.0.1 port 6969 after 0 ms: Connection refused**. My internet connection has no issues and I don't know why I'm getting this error.

![Screenshot from 2022-09-26 03-26-46](https://user-images.githubusercontent.com/55847410/192167347-ed9a4766-60a3-401d-86ec-a7a060875c28.png).

**Comment by AlbertoCanoD** [comment]
I have the same problem.

**Comment by cerg2010cerg2010** [comment]
That happens because Anisette server is not statically built and requires `libplist.so.3` library: `/tmp/anisette_server-x86_64: error while loading shared libraries: libplist.so.3: cannot open shared object file: No such file or directory`

On Arch there's `libplist` package which contains `libplist-2.0.so.3` and `libplist++-2.0.so.3` libraries, but it doesn't have `libplist.so.3` which is required. However, looking at Anisette server's CMake scripts, it should be compatible with both versions ([see here](https://github.com/Dadoum/Provision/blob/main/CMakeLists.txt#L19-L25))

So there are multiple ways to fix this:
1. Rebuild the server from sources using correct libraries
2. Symlink the library to the new name
3. Patch the binary somehow

**Comment by Dadoum** [comment]
An easy workaround is to replace anisette_server binary with the latest one. I added a [workaround](https://github.com/Dadoum/Provision/commit/9693321b8397a0d97614f805efc9843e410d333d) to this problem in Provision.

**Comment by maxasix** [comment]
This should be fixed now.
Remove the contents of the $HOME/.local/share/altlinux folder and try running the script without installing.
